### ----------------------------
### User Endpoints
### ----------------------------

### Place Order
POST http://localhost:5518/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTQzODhlYjdkZTU4MGVkZTY0OTg1OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU2MDI5NTExLCJleHAiOjE3NTYwMzMxMTF9.r322h3n32o25pNlWMjeSnoW22b6YSomkQLwigzU5jzI

{
  "userId": "68a4388eb7de580ede649859",
  "restaurantId": "68a23988bb5b07bed06d81af",
  "cart": [
    {
      "menuItemId": "68a23988bb5b07bed06d8a0c",
      "quantity": 2
    }
  ],
  "customerName": "User 1",
  "phone": "+49123456789",
  "address": "Musterstraße 1, Berlin",
  "deliveryType": "delivery",
  "paymentMethod": "card"
}

### Get all Order (user)
GET http://localhost:5517/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWVlODJjNTYyYWM0ZTg5NzNmMzY4YyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NDkwODY2LCJleHAiOjE3NTc0OTQ0NjZ9.XtFuOvuypA1rTa9zr5tbupzvUf3iW94La0m3QpnkGE8


### Get Order History
GET http://localhost:5517/orders/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWVlODJjNTYyYWM0ZTg5NzNmMzY4YyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NDkwODY2LCJleHAiOjE3NTc0OTQ0NjZ9.XtFuOvuypA1rTa9zr5tbupzvUf3iW94La0m3QpnkGE8

### Get Order Details
GET http://localhost:5517/orders/details/68bb3e83fc16b3f6335cef88
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWVlODJjNTYyYWM0ZTg5NzNmMzY4YyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NDkwODY2LCJleHAiOjE3NTc0OTQ0NjZ9.XtFuOvuypA1rTa9zr5tbupzvUf3iW94La0m3QpnkGE8

### Cancel Order (User)
PUT http://localhost:5517/orders/cancel/68bb3e83fc16b3f6335cef88
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWVlODJjNTYyYWM0ZTg5NzNmMzY4YyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NDkwODY2LCJleHAiOjE3NTc0OTQ0NjZ9.XtFuOvuypA1rTa9zr5tbupzvUf3iW94La0m3QpnkGE8

### ----------------------------
### Admin Endpoints
### ----------------------------

### Get all Orders (Admin)
GET http://localhost:5517/admin/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTMzODA3MDE3MDA2OTdiYzc3OWZkMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NzUxODMyMywiZXhwIjoxNzU3NTIxOTIzfQ.j5Zpq2ztbVOt9lew7rolz8F3pvkD5cIIg6A_R6VV9BA

### Change Order Status (Admin)
PUT http://localhost:5517/admin/orders/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTMzODA3MDE3MDA2OTdiYzc3OWZkMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NzUxODMyMywiZXhwIjoxNzU3NTIxOTIzfQ.j5Zpq2ztbVOt9lew7rolz8F3pvkD5cIIg6A_R6VV9BA

{
  "orderId": "68adf2fb2733d593a98203ee",
  "newStatus": "ready"
} 
### Get Order Details (Admin)
GET http://localhost:5517/admin/orders/details/68adf2fb2733d593a98203ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTMzODA3MDE3MDA2OTdiYzc3OWZkMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NzUxODMyMywiZXhwIjoxNzU3NTIxOTIzfQ.j5Zpq2ztbVOt9lew7rolz8F3pvkD5cIIg6A_R6VV9BA

### Delete Order (Admin)
DELETE http://localhost:5517/admin/orders/68a9e29d328b2394552e816e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTMzODA3MDE3MDA2OTdiYzc3OWZkMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NjA0ODYyOCwiZXhwIjoxNzU2MDUyMjI4fQ.Een91NlCu_uOi4lFPC8oeGkjYbt9Infnm36lgHSVGyM


### ----------------------------
### Owner Endpoint
### ----------------------------
GET http://localhost:5517/owner/restaurants/my-restaurant/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjVhMTA2MjlhZTQ1NmNhNjM3NjE4MSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU3NTE2Mzc2LCJleHAiOjE3NTc1MTk5NzZ9.hAKpY3ITU7KK4IKB0d_rQXQMWqYTOJ8w43pp85K2Ge0

### Change Order Status (Owner)
PUT http://localhost:5517/owner/restaurants/my-restaurant/orders/update-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjVhMTA2MjlhZTQ1NmNhNjM3NjE4MSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU3NTE2Mzc2LCJleHAiOjE3NTc1MTk5NzZ9.hAKpY3ITU7KK4IKB0d_rQXQMWqYTOJ8w43pp85K2Ge0

{
  "orderId": "68a9e9db2f78158ba2c44612",
  "newStatus": "preparing"
} 

### Get Order Details (Owner)
GET http://localhost:5517/owner/restaurants/my-restaurant/orders/details/68a9e9db2f78158ba2c44612
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjVhMTA2MjlhZTQ1NmNhNjM3NjE4MSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU3NTE2Mzc2LCJleHAiOjE3NTc1MTk5NzZ9.hAKpY3ITU7KK4IKB0d_rQXQMWqYTOJ8w43pp85K2Ge0

### Delete Order (Owner)
DELETE http://localhost:5517/owner/restaurants/my-restaurant/orders/68a9dcd5701e3bc6ace28e2b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjVhMTA2MjlhZTQ1NmNhNjM3NjE4MSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU3NTE2Mzc2LCJleHAiOjE3NTc1MTk5NzZ9.hAKpY3ITU7KK4IKB0d_rQXQMWqYTOJ8w43pp85K2Ge0

